// Code generated by Kitex v0.8.0. DO NOT EDIT.
package userhandler

import (
	server "github.com/cloudwego/kitex/server"
	user "github.com/Asong6824/douyin-user-service/kitex_gen/user"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler user.UserHandler, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
